### ISSUE TITLE
Install / implement via CDN

### ISSUE THREAD

**Issue by zarpio** [phoenixwong/vue2-timepicker#123]
How to install it directly with CDN URL?
Like I have installed vuejs via cdn.

`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>`

Please describe all the steps with example thanks.

**Comment by phoenixwong** [comment]
Please check the [comment here](https://github.com/phoenixwong/vue2-timepicker/issues/103#issuecomment-577726833)

Duplicates #103

**Comment by zarpio** [comment]
It helped me but can you please also guide how to import it thanks.

Following statement giving me an error.
`import VueTimepicker from 'vue2-timepicker'`
**Uncaught SyntaxError: Cannot use import statement outside a module**

**Comment by zarpio** [comment]
tried various ways... I am confused, a little full example code can help.

 ```
       //import VueTimepicker from 'vue2-timepicker'
        new Vue({
            el: '#app',
            // components: {
            //     vue-timepicker: window['vue2-timepicker']
            // },
            components: { VueTimepicker: window['vue2-timepicker'] },
            data: {
                days: {
                    time: []
                }
            },

            methods: {

            }
        });
```

**Comment by phoenixwong** [comment]
In your demo code, change `components: { VueTimepicker: window['vue2-timepicker'] }` to:

```
components: { VueTimepicker: VueTimepicker.default }
```

So that the entire HTML block becomes (note that I've also changed the VueTimepicker version from `1.0.8` to the latest `1.1.3`) -- 

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://unpkg.com/vue2-timepicker@1.1.3/dist/VueTimepicker.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="app">
  {{ hello }}
  <vue-timepicker></vue-timepicker>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" type="text/javascript"></script>
<script src="https://unpkg.com/vue2-timepicker@1.1.3/dist/VueTimepicker.umd.min.js" type="text/javascript"></script>
<script>

new Vue({
    el: '#app',
    components: { VueTimepicker: VueTimepicker.default },
    data: {
      hello: "Hello world! Testing"
    }
});
  </script>
</body>
</html>
```

<img width="1659" alt="JSBin-issue-123" src="https://user-images.githubusercontent.com/6954306/85220770-f30d4200-b3e0-11ea-90ae-6e163663bebb.png">

**Comment by zarpio** [comment]
**Thanks** :-) now it is working.

Can you please guide, how to determine in VueJs components which type of component should be loaded/import by what method, as you can see I have used several methods to import. Problem is in every single component they used to be different methods to be imported/implemented, why?

**Comment by phoenixwong** [comment]
Basically, the `import XX from YY` works for bundlers -- Vue-Cli (Webpack), Parcel, etc. And the `.default` suffix is not needed when implementing the `import` method. Use `components: { VueTimepicker }` as mentioned in the [documentation](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#step-2-include-vuetimepicker-in-your-component) will do.

Please note that not every Vue plugin uses the same export/rollup tool, so the above CDN trick might not work for all. I'm afraid you'll have to ask the other plugin author for help if you met any CDN related issue again.

That's why I recommend using bundlers instead of CDN. With a bundler, you should be able to use `import` to load most vue plugins without a problem.
