### ISSUE TITLE
Is it possible for you to add two more props for opening and closing the dropdown programatically ?

### ISSUE THREAD

**Issue by MadhuPolu** [phoenixwong/vue2-timepicker#126]

**Comment by phoenixwong** [comment]
You can get it done with the following steps:

```html
<!-- 1. Add "ref" to the timepicker you want to control -->
<vue-timepicker ref="myTimePicker"></vue-timepicker>
```

```javascript
// 2. Call the next line whenever you want to toggle the dropdown (For v.1.1.3+)
this.$refs.myTimePicker.toggleActive()
```

Here's a brief [JSFiddle demo](https://jsfiddle.net/phoenixwong/3Lu8ko65/) with v1.1.3.

**Comment by MadhuPolu** [comment]
Thanks @phoenixwong, but there is small issue that two dropdown are opening at a time, but not closing at same. Plz check this https://jsfiddle.net/cosmos_madhu/tg8eh60s/2/

**Comment by phoenixwong** [comment]
Hi @MadhuPolu,

It's because, in your demo, the toggle button's **z-index** is lower than the transparent overlay mask of those two opened Timepickers. This means when you click on the `<button>` with two Timepickers' opening, you are actually clicking on one of the Timepicker's overlay mask.

I updated [my JSFiddle demo](https://jsfiddle.net/phoenixwong/3Lu8ko65/) for a bit. In the new example, I use a `setTimeout()` to programmatically auto-close two dropdowns after 5s.

If you want to use a button for closing all dropdowns, you'll need to make sure that the button is clickable, E.g. have a higher z-index than the overlay.

**Comment by MadhuPolu** [comment]
hey @phoenixwong, Thanks that z-index working partially for my requirement, actually the below workaround suits for my requirement. Thanks a lot, 'vue2-timepicker' is really a great package. Kudos!!

.time-picker-overlay {
    display: none !important;
}
