### ISSUE TITLE
Why you set a muteFlowListener?

### ISSUE THREAD

**Issue by zzz6519003** [phoenixwong/vue2-timepicker#7]
```js
    window.setTimeout(() => {
      self.muteFlowListener = false
    }, 1000)
```
👍

**Comment by phoenixwong** [comment]
If not doing so, it will cause an infinite loop.

P.S. Since you are already playing around with the Demo pages, I'd suggest you try comment out (`//`) some lines you've been curious about, or try `console.log` some results and see what will happen. That will be more fun than requesting for answers.

**Comment by zzz6519003** [comment]
plus I think there shouldn't be an infinite loop
