### ISSUE TITLE
Touchpad tap to click not working

### ISSUE THREAD

**Issue by rjurado01** [phoenixwong/vue2-timepicker#78]
When I click hour from selector using tap to click, the selector is closed and hour is not selected.
It's very strange as when I use normal click it works.

Browser: Firefox / Chrome
SO: Windows 10
Version: 1.0.0 (tested into [example page](https://phoenixwong.github.io/vue2-timepicker/))

**Comment by phoenixwong** [comment]
Hi @rjurado01,

I don't have a touchpad device around me at this moment, so I can only make assumptions base on past experiences:

1. Somehow the `tap` event is fired instead of `click`. Which is an annoying problem in the old days, but it should not be a problem on modern devices with a trendy browser.
2. When tapping an hour value item, the `hover` effect is triggered (the target value item's background turn gray, not green). You'll need to tap for a second time to trigger the `click` event. This is also a mobile device related issue. However, as you mentioned, the dropdown already closed after the first tap, which is odd indeed.

Can you provide your device's **brand and model**, like "Surface XXX" for example? Just for reference. Along with the **Firefox / Chrome version** you used. I need more information to do further debugging. Thanks!

**Comment by rjurado01** [comment]
My laptop is: Lenovo Ideapad s540
OS: Windows 10
Chrome version: 77.0.3865
Firefox version: 69.01

To my surprise I have tested it in Ubuntu (same laptop) and in other laptops (Windows) and it works so I'm so confused. It seems that is Windows problem for my laptop.

**Comment by phoenixwong** [comment]
Thanks for the followed up information, @rjurado01.

I'll try to create a JSFiddle for debugging your touchpad event later and keep you posted.

**Comment by phoenixwong** [comment]
Hi @rjurado01, 

I created a [JSFiddle here](https://jsfiddle.net/phoenixwong/v8xzft0o/) for debugging your touchpad.

It's a minimum reproduction of the current vue2-timepicker. Same div + CSS structure. Whereas, instead of `click`, I also added `touchstart` and `touchend` event listeners in the fiddle demo. 

Theoretically, _touch_ events only exist on touchscreen behaviours (smartphone, tablet, etc). Using a touchpad on a laptop should not trigger _touch_ events.

If you can see *touch* events on your Windows + touchpad, then it might be the main cause of your reported issue.

Please let me know.

**Comment by rjurado01** [comment]
The JSFiddle example works ok

![image](https://user-images.githubusercontent.com/1703608/67799878-837bc880-fa86-11e9-92e4-80861f7fc19d.png)

But the example web doesn't. 
![no-select](https://user-images.githubusercontent.com/1703608/67799935-9ee6d380-fa86-11e9-9654-44db8c389979.gif)

**Comment by rjurado01** [comment]
The error is that `onBlur` function is called when click select option before to call `select`.
If I increase `delay` to `300` used into `debounceBlur` method it works.

I have see that there is a prop for this purpose.

**Comment by phoenixwong** [comment]
Nice catch! 👍 

So somehow, the Windows + touchpad clicks on your device got a latency > 200ms and <= 300ms. It sounds a bit like the 300ms `touchend` latency on a touch-screen Webkit browser, although it's not a `touchend` event.

I'm considering adjusting the default value of `blur-delay` from `200` to `300`. Will do some more tests later.
